// ─────────────────────────────────────────────
//  NEEV Demo Data — hardcoded sample dataset
//  Used in Demo Mode to bypass Firebase/Auth
// ─────────────────────────────────────────────

export const DEMO_NGO = {
  id: 'ngo_001',
  name: 'Seva Foundation',
  email: 'admin@sevafoundation.org',
  city: 'Mumbai',
  totalNeedsPosted: 5,
  impactScore: 87,
};

export const DEMO_VOLUNTEER = {
  id: 'vol_001',
  name: 'Priya Sharma',
  email: 'priya@example.com',
  skills: ['Teaching', 'Hindi speaking', 'First Aid', 'Computer skills'],
  city: 'Mumbai',
  hoursPerWeek: 8,
  tasksCompleted: 3,
  totalImpactHours: 24,
  rating: 4.8,
  joinedAt: '2025-11-15',
};

export const DEMO_NEEDS = [
  {
    id: 'need_001',
    ngoId: 'ngo_001',
    ngoName: 'Seva Foundation',
    title: 'Free Medical Camp — Dharavi',
    description:
      'We are organizing a free medical camp in Dharavi, Mumbai to provide basic health check-ups, medication distribution, and health awareness to 300+ residents. Volunteers must be comfortable working in a high-density slum environment and ideally have medical or first-aid knowledge.',
    category: 'Medical',
    location: { city: 'Mumbai', lat: 19.0396, lng: 72.8527 },
    urgency: 'High',
    volunteersNeeded: 4,
    volunteersAssigned: ['vol_002', 'vol_005'],
    status: 'open',
    createdAt: '2026-04-10T08:00:00Z',
    requiredSkills: ['Medical', 'First Aid', 'Hindi speaking'],
  },
  {
    id: 'need_002',
    ngoId: 'ngo_002',
    ngoName: 'Chennai Relief Network',
    title: 'Flood Relief Packing — Tambaram',
    description:
      'Urgently need volunteers to pack and distribute relief kits (food, water, medicine) for flood-affected families in Tambaram. Physical stamina required. Tamil speakers given preference for ground coordination.',
    category: 'Disaster Relief',
    location: { city: 'Chennai', lat: 12.9249, lng: 80.1000 },
    urgency: 'High',
    volunteersNeeded: 8,
    volunteersAssigned: ['vol_003'],
    status: 'open',
    createdAt: '2026-04-09T14:00:00Z',
    requiredSkills: ['Physical labor', 'Tamil speaking', 'Logistics'],
  },
  {
    id: 'need_003',
    ngoId: 'ngo_003',
    ngoName: 'Digital Bharat Trust',
    title: 'Digital Literacy Workshop — Bengaluru',
    description:
      'Conduct a 3-day digital literacy workshop for 60 women from low-income households. Topics include smartphone basics, UPI payments, government app usage, and online safety. Venue arranged in Rajajinagar.',
    category: 'Education',
    location: { city: 'Bengaluru', lat: 12.9716, lng: 77.5946 },
    urgency: 'Medium',
    volunteersNeeded: 2,
    volunteersAssigned: ['vol_001'],
    status: 'active',
    createdAt: '2026-04-08T10:00:00Z',
    requiredSkills: ['Teaching', 'Computer skills', 'Kannada/Hindi'],
  },
  {
    id: 'need_004',
    ngoId: 'ngo_004',
    ngoName: "Shakti Women's Collective",
    title: "Women's Self-Defense Classes — Delhi",
    description:
      "Running monthly free self-defense workshops for women aged 16–40 in South Delhi. Looking for certified martial arts instructors or trained fitness professionals. Hindi and Urdu speaking preferred for effective communication.",
    category: 'Women Empowerment',
    location: { city: 'Delhi', lat: 28.6139, lng: 77.2090 },
    urgency: 'Medium',
    volunteersNeeded: 3,
    volunteersAssigned: [],
    status: 'open',
    createdAt: '2026-04-07T09:00:00Z',
    requiredSkills: ['Martial arts', 'Hindi speaking', 'Fitness training'],
  },
  {
    id: 'need_005',
    ngoId: 'ngo_005',
    ngoName: 'HariyaLi Hyderabad',
    title: 'Tree Plantation Drive — Shamirpet',
    description:
      'Join our quarterly tree plantation drive at Shamirpet Lake, Hyderabad. We aim to plant 500 saplings. No prior experience needed — just enthusiasm, energy, and love for the environment! Breakfast and t-shirts provided.',
    category: 'Environment',
    location: { city: 'Hyderabad', lat: 17.5619, lng: 78.5565 },
    urgency: 'Low',
    volunteersNeeded: 10,
    volunteersAssigned: ['vol_004', 'vol_006', 'vol_007'],
    status: 'open',
    createdAt: '2026-04-06T07:00:00Z',
    requiredSkills: [],
  },
];

export const DEMO_VOLUNTEERS = [
  {
    id: 'vol_001',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    skills: ['Teaching', 'Hindi speaking', 'First Aid', 'Computer skills'],
    city: 'Mumbai',
    hoursPerWeek: 8,
    tasksCompleted: 3,
    totalImpactHours: 24,
    rating: 4.8,
    joinedAt: '2025-11-15',
  },
  {
    id: 'vol_002',
    name: 'Dr. Ravi Menon',
    email: 'ravi@example.com',
    skills: ['Medical', 'First Aid', 'Malayalam speaking', 'Hindi speaking'],
    city: 'Mumbai',
    hoursPerWeek: 6,
    tasksCompleted: 7,
    totalImpactHours: 42,
    rating: 4.9,
    joinedAt: '2025-08-01',
  },
  {
    id: 'vol_003',
    name: 'Kavitha Raj',
    email: 'kavitha@example.com',
    skills: ['Tamil speaking', 'Physical labor', 'Logistics', 'Cooking'],
    city: 'Chennai',
    hoursPerWeek: 12,
    tasksCompleted: 5,
    totalImpactHours: 60,
    rating: 4.7,
    joinedAt: '2025-09-20',
  },
  {
    id: 'vol_004',
    name: 'Aditya Joshi',
    email: 'aditya@example.com',
    skills: ['Physical labor', 'Environment', 'Hindi speaking', 'Photography'],
    city: 'Hyderabad',
    hoursPerWeek: 5,
    tasksCompleted: 2,
    totalImpactHours: 10,
    rating: 4.5,
    joinedAt: '2026-01-10',
  },
  {
    id: 'vol_005',
    name: 'Nusrat Khan',
    email: 'nusrat@example.com',
    skills: ['Nursing', 'First Aid', 'Urdu speaking', 'Hindi speaking'],
    city: 'Delhi',
    hoursPerWeek: 10,
    tasksCompleted: 4,
    totalImpactHours: 32,
    rating: 4.6,
    joinedAt: '2025-12-05',
  },
  {
    id: 'vol_006',
    name: 'Sanjay Patel',
    email: 'sanjay@example.com',
    skills: ['Environment', 'Gardening', 'Gujarati speaking', 'Hindi speaking'],
    city: 'Hyderabad',
    hoursPerWeek: 8,
    tasksCompleted: 6,
    totalImpactHours: 48,
    rating: 4.8,
    joinedAt: '2025-10-14',
  },
  {
    id: 'vol_007',
    name: 'Ananya Krishnan',
    email: 'ananya@example.com',
    skills: ['Teaching', 'Computer skills', 'Tamil speaking', 'English'],
    city: 'Bengaluru',
    hoursPerWeek: 15,
    tasksCompleted: 9,
    totalImpactHours: 72,
    rating: 5.0,
    joinedAt: '2025-07-22',
  },
  {
    id: 'vol_008',
    name: 'Farhan Siddiqui',
    email: 'farhan@example.com',
    skills: ['Martial arts', 'Fitness training', 'Hindi speaking', 'Urdu speaking'],
    city: 'Delhi',
    hoursPerWeek: 7,
    tasksCompleted: 1,
    totalImpactHours: 7,
    rating: 4.4,
    joinedAt: '2026-02-28',
  },
];

export const DEMO_ASSIGNMENTS = [
  {
    id: 'asgn_001',
    needId: 'need_001',
    volunteerId: 'vol_002',
    assignedAt: '2026-04-10T09:25:00Z',
    completedAt: null,
    status: 'accepted',
  },
  {
    id: 'asgn_002',
    needId: 'need_003',
    volunteerId: 'vol_001',
    assignedAt: '2026-04-08T11:00:00Z',
    completedAt: '2026-04-13T17:00:00Z',
    status: 'completed',
  },
];

// Mock Gemini responses for demo mode
export const MOCK_MATCH_RESULTS = {
  need_001: {
    matches: [
      {
        volunteerId: 'vol_002',
        name: 'Dr. Ravi Menon',
        matchScore: 97,
        matchedSkills: ['Medical', 'First Aid', 'Hindi speaking'],
        reason: 'Dr. Menon is a medical professional based in Mumbai with direct first-aid expertise and Hindi fluency — an ideal fit for the Dharavi health camp.',
        estimatedImpact: '~10 hrs, 80+ patients served',
      },
      {
        volunteerId: 'vol_005',
        name: 'Nusrat Khan',
        matchScore: 88,
        matchedSkills: ['First Aid', 'Hindi speaking'],
        reason: 'Nusrat brings nursing skills and bilingual ability in Hindi & Urdu, making her excellent for patient communication and medication guidance.',
        estimatedImpact: '~8 hrs, 60+ patients',
      },
      {
        volunteerId: 'vol_001',
        name: 'Priya Sharma',
        matchScore: 74,
        matchedSkills: ['First Aid', 'Hindi speaking'],
        reason: 'Priya has first-aid training and is city-local in Mumbai, reducing travel time and making her a reliable support volunteer.',
        estimatedImpact: '~6 hrs, health awareness sessions',
      },
    ],
  },
  need_002: {
    matches: [
      {
        volunteerId: 'vol_003',
        name: 'Kavitha Raj',
        matchScore: 99,
        matchedSkills: ['Tamil speaking', 'Physical labor', 'Logistics'],
        reason: 'Kavitha is based in Chennai with all required skills and prior relief experience — the highest possible match for this flood relief operation.',
        estimatedImpact: '~16 hrs, 200 relief kits packed',
      },
      {
        volunteerId: 'vol_004',
        name: 'Aditya Joshi',
        matchScore: 62,
        matchedSkills: ['Physical labor'],
        reason: 'Aditya has physical stamina and experience with outdoor community work, though lacks Tamil language skills needed for local coordination.',
        estimatedImpact: '~10 hrs, logistics support',
      },
      {
        volunteerId: 'vol_006',
        name: 'Sanjay Patel',
        matchScore: 55,
        matchedSkills: ['Physical labor'],
        reason: 'Sanjay offers physical effort and community event experience, though his skill alignment is partial for this specific relief task.',
        estimatedImpact: '~8 hrs, packing assistance',
      },
    ],
  },
};

export const MOCK_IMPACT_REPORT =
  "This month, NEEV volunteers contributed over 82 hours of meaningful service across Mumbai and Bengaluru — reaching more than 340 community members through medical outreach and digital literacy workshops. Three high-urgency needs were addressed within 48 hours of posting, demonstrating the platform's real-time matching efficiency. The collective impact of these collaborations has earned Seva Foundation a community impact score of 87, reflecting deep trust and sustained volunteer engagement.";
